# Пустые ячейки в таблице и восстановление данных

In [1]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/students.csv', delimiter=',')
df['Weight'].describe()

count    157.000000
mean      64.031847
std       16.502300
min        3.000000
25%       53.000000
50%       60.000000
75%       71.000000
max      120.000000
Name: Weight, dtype: float64

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

Удаление объектов/столбцов с отсутствующими данными

In [3]:
df1=df.dropna()
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          118 non-null    int64
 1   Growth                       118 non-null    int64
 2   Shoe size                    118 non-null    int64
 3   Course number                118 non-null    int64
 4   Year of birth                118 non-null    int64
 5   Friend number                118 non-null    int64
 6   Russian rating               118 non-null    int64
 7   Maths rating                 118 non-null    int64
 8   Physics rating               118 non-null    int64
 9   Computer science rating      118 non-null    int64
 10  Chemistry rating             118 non-null    int64
 11  Literature rating            118 non-null    int64
 12  History rating               118 non-null    int64
 13  Geography rating             118 non-null    int64
 14  Biology rating               118 non-null    int64
 15  Foreign language rating      118 non-null    int64
 16  Social science rating        118 non-null    int64
 17  Distance to home km          118 non-null    int64
 18  Minutes to first class       118 non-null    int64
 19  Children number              118 non-null    float64
 20  Removed teeth                118 non-null    float64
 21  Weight                       118 non-null    float64
 22  Glasses                      118 non-null    object
 23  Sex                          118 non-null    object
 24  Problems in last semester    118 non-null    object
 25  Coin                         118 non-null    object
 26  Rock paper scissors          118 non-null    object
 27  Animal                       118 non-null    object
 28  Month of birthday            118 non-null    int64
 29  Your rating in university    118 non-null    object
 30  Fastfood                     118 non-null    object
 31  Height of 5000 mm            118 non-null    int64
 32  Width of 5000 mm             118 non-null    int64
 33  Putin age                    118 non-null    int64
 34  Army                         118 non-null    object
 35  Hostel                       118 non-null    object
 36  Hair length                  118 non-null    float64
 37  Floor number                 118 non-null    int64
 38  Social network duration min  118 non-null    int64
 39  Chocolate                    118 non-null    object
 40  City population              118 non-null    float64
 41  Strange people               118 non-null    object
 42  Your insitute                118 non-null    object
 43  Brother-sister               118 non-null    object
 44  Plane seat                   118 non-null    object
 45  MIddle and index finger      118 non-null    int64
 46  Middle and ring finger       118 non-null    float64
 47  Middle and little finger     118 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 45.2+ KB

In [4]:
df=df.dropna()
#теперь в  таблице df лежат студенты, у которых нет пропусков в данных

In [5]:
df=df.fillna(0)
#теперь в  таблице df лежат студенты, у которых пропуски в признаках заполнены 0

In [6]:
df=df.fillna(df.mean)
#теперь в  таблице df лежат студенты, у которых пропуски в признаках заполнены средним значением по столбцу

Замена пропущенные значения

In [7]:
df2=df.fillna(0)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          118 non-null    int64
 1   Growth                       118 non-null    int64
 2   Shoe size                    118 non-null    int64
 3   Course number                118 non-null    int64
 4   Year of birth                118 non-null    int64
 5   Friend number                118 non-null    int64
 6   Russian rating               118 non-null    int64
 7   Maths rating                 118 non-null    int64
 8   Physics rating               118 non-null    int64
 9   Computer science rating      118 non-null    int64
 10  Chemistry rating             118 non-null    int64
 11  Literature rating            118 non-null    int64
 12  History rating               118 non-null    int64
 13  Geography rating             118 non-null    int64
 14  Biology rating               118 non-null    int64
 15  Foreign language rating      118 non-null    int64
 16  Social science rating        118 non-null    int64
 17  Distance to home km          118 non-null    int64
 18  Minutes to first class       118 non-null    int64
 19  Children number              118 non-null    float64
 20  Removed teeth                118 non-null    float64
 21  Weight                       118 non-null    float64
 22  Glasses                      118 non-null    object
 23  Sex                          118 non-null    object
 24  Problems in last semester    118 non-null    object
 25  Coin                         118 non-null    object
 26  Rock paper scissors          118 non-null    object
 27  Animal                       118 non-null    object
 28  Month of birthday            118 non-null    int64
 29  Your rating in university    118 non-null    object
 30  Fastfood                     118 non-null    object
 31  Height of 5000 mm            118 non-null    int64
 32  Width of 5000 mm             118 non-null    int64
 33  Putin age                    118 non-null    int64
 34  Army                         118 non-null    object
 35  Hostel                       118 non-null    object
 36  Hair length                  118 non-null    float64
 37  Floor number                 118 non-null    int64
 38  Social network duration min  118 non-null    int64
 39  Chocolate                    118 non-null    object
 40  City population              118 non-null    float64
 41  Strange people               118 non-null    object
 42  Your insitute                118 non-null    object
 43  Brother-sister               118 non-null    object
 44  Plane seat                   118 non-null    object
 45  MIddle and index finger      118 non-null    int64
 46  Middle and ring finger       118 non-null    float64
 47  Middle and little finger     118 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 45.2+ KB

Замена пропущенного значения на среднее по столбцу (или на медиану\\)

In [8]:
df3=df.fillna(df.median)
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          118 non-null    int64
 1   Growth                       118 non-null    int64
 2   Shoe size                    118 non-null    int64
 3   Course number                118 non-null    int64
 4   Year of birth                118 non-null    int64
 5   Friend number                118 non-null    int64
 6   Russian rating               118 non-null    int64
 7   Maths rating                 118 non-null    int64
 8   Physics rating               118 non-null    int64
 9   Computer science rating      118 non-null    int64
 10  Chemistry rating             118 non-null    int64
 11  Literature rating            118 non-null    int64
 12  History rating               118 non-null    int64
 13  Geography rating             118 non-null    int64
 14  Biology rating               118 non-null    int64
 15  Foreign language rating      118 non-null    int64
 16  Social science rating        118 non-null    int64
 17  Distance to home km          118 non-null    int64
 18  Minutes to first class       118 non-null    int64
 19  Children number              118 non-null    float64
 20  Removed teeth                118 non-null    float64
 21  Weight                       118 non-null    float64
 22  Glasses                      118 non-null    object
 23  Sex                          118 non-null    object
 24  Problems in last semester    118 non-null    object
 25  Coin                         118 non-null    object
 26  Rock paper scissors          118 non-null    object
 27  Animal                       118 non-null    object
 28  Month of birthday            118 non-null    int64
 29  Your rating in university    118 non-null    object
 30  Fastfood                     118 non-null    object
 31  Height of 5000 mm            118 non-null    int64
 32  Width of 5000 mm             118 non-null    int64
 33  Putin age                    118 non-null    int64
 34  Army                         118 non-null    object
 35  Hostel                       118 non-null    object
 36  Hair length                  118 non-null    float64
 37  Floor number                 118 non-null    int64
 38  Social network duration min  118 non-null    int64
 39  Chocolate                    118 non-null    object
 40  City population              118 non-null    float64
 41  Strange people               118 non-null    object
 42  Your insitute                118 non-null    object
 43  Brother-sister               118 non-null    object
 44  Plane seat                   118 non-null    object
 45  MIddle and index finger      118 non-null    int64
 46  Middle and ring finger       118 non-null    float64
 47  Middle and little finger     118 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 45.2+ KB

In [9]:
df['Children number']=df['Children number'].fillna(df['Children number'].mean())
# заполнить пропуски в признаке "Количество детей" средним значением по столбцу

Как пропуски в одном признаке заменить по одному правилу, а пропуски во втором столбце - по другому правилу.

In [10]:
df['Weight']=df['Weight'].fillna(df['Weight'].mean())
df['Children number']=df['Children number'].fillna(0)
df['Removed teeth']=df['Removed teeth'].fillna(df['Removed teeth'].median())
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 118 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          118 non-null    int64
 1   Growth                       118 non-null    int64
 2   Shoe size                    118 non-null    int64
 3   Course number                118 non-null    int64
 4   Year of birth                118 non-null    int64
 5   Friend number                118 non-null    int64
 6   Russian rating               118 non-null    int64
 7   Maths rating                 118 non-null    int64
 8   Physics rating               118 non-null    int64
 9   Computer science rating      118 non-null    int64
 10  Chemistry rating             118 non-null    int64
 11  Literature rating            118 non-null    int64
 12  History rating               118 non-null    int64
 13  Geography rating             118 non-null    int64
 14  Biology rating               118 non-null    int64
 15  Foreign language rating      118 non-null    int64
 16  Social science rating        118 non-null    int64
 17  Distance to home km          118 non-null    int64
 18  Minutes to first class       118 non-null    int64
 19  Children number              118 non-null    float64
 20  Removed teeth                118 non-null    float64
 21  Weight                       118 non-null    float64
 22  Glasses                      118 non-null    object
 23  Sex                          118 non-null    object
 24  Problems in last semester    118 non-null    object
 25  Coin                         118 non-null    object
 26  Rock paper scissors          118 non-null    object
 27  Animal                       118 non-null    object
 28  Month of birthday            118 non-null    int64
 29  Your rating in university    118 non-null    object
 30  Fastfood                     118 non-null    object
 31  Height of 5000 mm            118 non-null    int64
 32  Width of 5000 mm             118 non-null    int64
 33  Putin age                    118 non-null    int64
 34  Army                         118 non-null    object
 35  Hostel                       118 non-null    object
 36  Hair length                  118 non-null    float64
 37  Floor number                 118 non-null    int64
 38  Social network duration min  118 non-null    int64
 39  Chocolate                    118 non-null    object
 40  City population              118 non-null    float64
 41  Strange people               118 non-null    object
 42  Your insitute                118 non-null    object
 43  Brother-sister               118 non-null    object
 44  Plane seat                   118 non-null    object
 45  MIddle and index finger      118 non-null    int64
 46  Middle and ring finger       118 non-null    float64
 47  Middle and little finger     118 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 45.2+ KB

Заполнение пропусков в категориальных признаках

In [11]:
df['Glasses'].value_counts()

Glasses
нет                                    58
да                                     55
простите. не увидел(а) вопроса ))))     5
Name: count, dtype: int64

In [12]:
df['Glasses']=df['Glasses'].fillna('да')
df['Glasses'].value_counts()

Glasses
нет                                    58
да                                     55
простите. не увидел(а) вопроса ))))     5
Name: count, dtype: int64

In [13]:
female=df[df['Sex']=='женский'].copy()
male=df[df['Sex']=='мужской'].copy()
female['Weight']=female['Weight'].fillna(female['Weight'].mean())
male['Weight']=male['Weight'].fillna(male['Weight'].mean())
df_restored=female.appen
df_restored['Weight'].mean()

65.01694915254237

In [14]:
singles=df[df['Brother-sister']=='нет ни брата ни сестры'].copy()
sublings=df[df['Brother-sister']!='нет ни брата ни сестры'].copy()

In [15]:
singles['Children number'].median()

2.0

In [16]:
sublings['Children number'].median()

2.0

In [17]:
singles['Children number'].describe()

count      21.000000
mean       50.190476
std       223.132779
min         0.000000
25%         0.000000
50%         2.000000
75%         2.000000
max      1024.000000
Name: Children number, dtype: float64

In [18]:
sublings['Children number'].describe()

count    97.000000
mean      1.577320
std       1.175577
min       0.000000
25%       1.000000
50%       2.000000
75%       2.000000
max       6.000000
Name: Children number, dtype: float64

In [19]:
singles['Children number']=singles['Children number'].fillna(singles['Children number'].median())
sublings['Children number']=sublings['Children number'].fillna(sublings['Children number'].median())
df_restored1=pd.concat([singles, sublings])
df_restored1['Children number'].describe()

count     118.000000
mean       10.228814
std        94.130902
min         0.000000
25%         0.625000
50%         2.000000
75%         2.000000
max      1024.000000
Name: Children number, dtype: float64

In [20]:
df_restored1['Children number'].median()

2.0

In [21]:
df['Children number'].describe()

count     118.000000
mean       10.228814
std        94.130902
min         0.000000
25%         0.625000
50%         2.000000
75%         2.000000
max      1024.000000
Name: Children number, dtype: float64

In [22]:
df['Brother-sister'].value_counts()

Brother-sister
есть брат                 39
есть сестра               37
нет ни брата ни сестры    21
есть и брат и сестра      21
Name: count, dtype: int64

In [23]:
len(df)-df['Children number'].count()

0